### ISSUE TITLE
Suggestions for improvement Smart Meter 

### ISSUE THREAD

**Issue by schami23** [fhempy/fhempy#120]
Can this function be imported to read the values ​​from the Smart Meter in fhempy?

https://github.com/platysma/vienna-smartmeter

**Comment by fhempy** [comment]
Great idea! Unfortunately my flat hasn't a smart meter yet 😟 
Can you please provide me the output of - you can obfuscate the data, I just need the correct structure
```python
from vienna_smartmeter import Smartmeter
from datetime import datetime, timedelta

yesterday = datetime.now() - timedelta(days=1)

username = 'YOUR_LOGIN_USER_NAME'
password = 'YOUR_PASSWORD'

api = Smartmeter(username, password)
print(api.profil())
print(api.zaehlpunkte())
print(api.verbrauch(yesterday))
print(api.verbrauch_raw(yesterday))
print(api.verbrauch(datetime.now())
```

Please let me know if you opted-in for 15min consumption values or hourly/daily.

**Comment by schami23** [comment]
Sorry I didn't test it before.
https://github.com/platysma/vienna-smartmeter
no longer works, due to url changes.

Now use this: https://github.com/DarwinsBuddy/WienerNetzeSmartmeter/tree/main/custom_components/wnsm/api

But unfortunately it doesn't work properly, I keep getting the following error: {'Exception': 'PROD API Gateway encountered an error. Error Message: Unauthorized application request. Request Details: Service - WN_SMART_METER_PORTAL_API_B2C, Operation - /zaehlpunkte, Invocation Time:8:18:39 AM, Date:Jan 17, 2023, Client IP - ............, User - Default and Application:sys:defaultApplication'}

Unfortunately, I have limited Python knowledge. I'm trying to find the problem.

**Comment by schami23** [comment]
This works!!!

https://github.com/florianL21/vienna-smartmeter

Got the following output:

`{'id': 00000, 'salutation': 'Herr', 'lastname': 'Muster', 'firstname': 'Max', 'email': 'test@uster.at', 'defaultGeschaeftspartnerRegistration': {'id': 0000, 'registrationKey': '000000000', 'zaehlpunkt': 'AT001000000000000000100000000000', 'status': 'CONFIRMED', 'geschaeftspartner': '1201295070', 'completedAt': '2022-09-21T14:34:57.076Z'}, 'isZpsDonee': False}
[{'bezeichnung': 'Muster Max, Kundennummer 0000000', 'geschaeftspartner': '0000000', 'zaehlpunkte': [{'zaehlpunktnummer': 'AT001000000000000000100000000000000', 'customLabel': None, 'equipmentNumber': '0000000000', 'geraetNumber': 'ISK10000000000', 'isSmartMeter': True, 'isDefault': True, 'isActive': True, 'isDataDeleted': False, 'isSmartMeterMarketReady': True, 'dataDeletionTimestampUTC': None, 'verbrauchsstelle': {'strasse': 'Xygasse', 'hausnummer': '10', 'anlageHausnummer': '10', 'postleitzahl': '1010', 'ort': 'Wien', 'laengengrad': '16.000000', 'breitengrad': '50.00000000'}, 'anlage': {'typ': 'TAGSTROM'}, 'vertraege': [{'einzugsdatum': '2015-03-06', 'auszugsdatum': None}], 'idexStatus': {'granularity': {'status': 'DAY', 'canBeChanged': True}, 'customerInterface': {'status': 'inactive', 'canBeChanged': True}, 'display': {'isLocked': True, 'canBeChanged': True}, 'displayProfile': {'canBeChanged': True, 'displayProfile': 'VERBRAUCH'}}, 'optOutDetails': {'isOptOut': False}, 'zpSharingInfo': {'isOwner': False}}]}]
{'quarter-hour-opt-in': False, 'statistics': {'maximum': 0, 'minimum': 0, 'average': 0}}
{'quarter-hour-opt-in': True, 'statistics': {'maximum': 0, 'minimum': 0, 'average': 0}}`

The syntax of
`print(api.verbrauch(yesterday))
print(api.verbrauch_raw(yesterday))
print(api.verbrauch(datetime.now())`

it does not work

**Comment by schami23** [comment]
Here is the output from

print(api.welcome())

`{'hasSmartMeter': True, 'isDataDeleted': False, 'dataDeletionTimestampUTC': None, 'zaehlpunkt': {'zaehlpunktName': None, 'zaehlpunktnummer': 'AT0010000000000000001000000000000', 'zaehlpunktAnlagentyp': 'TAGSTROM', 'adresse': 'Xygasse 10, 1010 Wien', 'postleitzahl': '1010', 'meterReadings': [{'value': 1353079, 'type': '1-2:1.8.0', 'validated': True, 'date': '2023-01-15T23:00:00.000Z'}], 'pmaxReadings': [{'value': 0.0, 'type': '1-1:1.6.0', 'validated': False, 'startDate': None, 'endDate': None, 'range': 'DAY'}, {'value': 0.0, 'type': '1-1:1.6.0', 'validated': False, 'startDate': None, 'endDate': None, 'range': 'MONTH'}], 'consumptionYesterday': {'value': 14567, 'validated': True, 'date': '2023-01-15T23:00:00.000Z'}, 'consumptionDayBeforeYesterday': {'value': 17029, 'validated': True, 'date': '2023-01-14T23:00:00.000Z'}, 'optOutDetails': {'isOptOut': False}}}
`

The consumption of 
yesterday 14,567 Kw/h
and the 
day before yesterday 17,029 Kw/h

I have set the daily consumption.

**Comment by fhempy** [comment]
Great, thank you for finding a working library. The output looks pretty easy to integrate.

I think I should be able to provide a first working version next week.

**Comment by schami23** [comment]
Great. There was only one change in the API with this fix it works again.

https://github.com/DarwinsBuddy/WienerNetzeSmartmeter/commit/2d69c65e66501d7e3d909507c9eedc920ab88597

**Comment by fhempy** [comment]
I implemented the first version, can you please do a quick check if it works:
`define smartmeter fhempy wienernetze_smartmeter USERNAME PASSWORD`

First update fhempy to the latest version.

**Comment by schami23** [comment]
Thank you for your work! 

Unfortunately, Wienenergie has made changes to the API again (see link)

https://github.com/DarwinsBuddy/WienerNetzeSmartmeter/commit/7c65aa1b4c209d88cc9ad76e04ad96347b25f3a2#diff-2576a12d790bf1edd89ed3d105f35ae109ecddc57258b39c457058b9375b199d

client.py

`def consumptions(self):
        """Returns response from 'consumptions' endpoint."""
        return self._call_api("zaehlpunkt/consumptions")

    def base_information(self):
        """Returns response from 'baseInformation' endpoint."""
        return self._call_api("zaehlpunkt/baseInformation")

    def meter_readings(self):
        """Returns response from 'meterReadings' endpoint."""
        return self._call_api("zaehlpunkt/meterReadings")
`

print(api.welcome()) doesn't work anymore

the new parameters result in the following output

print(api.consumptions())
`{'consumptionYesterday': {'value': 13028, 'validated': True, 'date': '2023-02-24T23:00:00.000Z'}, 'consumptionDayBeforeYesterday': {'value': 14612, 'validated': True, 'date': '2023-02-23T23:00:00.000Z'}}`

print(api.base_information())
`{'hasSmartMeter': True, 'isDataDeleted': False, 'dataDeletionTimestampUTC': None, 'zaehlpunkt': {'zaehlpunktName': None, 'zaehlpunktnummer': 'AT001000000000000000100001000000', 'zaehlpunktAnlagentyp': 'TAGSTROM', 'adresse': 'Mustergasse 1, 1010 Wien', 'postleitzahl': '1010'}}
`
print(api.meter_readings())
`{'meterReadings': [{'value': 1837599, 'type': '1-2:1.8.0', 'validated': True, 'date': '2023-02-24T23:00:00.000Z'}]}
`

**Comment by fhempy** [comment]
Thx for pointing me to the api updates.

Please test the updated version - it's completely untested, as I don't have a smartmeter yet :(

**Comment by fhempy** [comment]
Actually you don't need to set update, that's just an old command which can be removed. Just after the define readings should appear automatically. Please let me know if there are any or if other errors occur.

**Comment by schami23** [comment]
Sorry, unfortunately there was a misunderstanding. I saw that you used the old parameters from https://github.com/florianL21/vienna-smartmeter in the script, which unfortunately no longer work.

https://github.com/DarwinsBuddy/WienerNetzeSmartmeter/commit/7c65aa1b4c209d88cc9ad76e04ad96347b25f3a2#diff-2576a12d790bf1edd89ed3d105f35ae109ecddc57258b39c457058b9375b199d

https://github.com/DarwinsBuddy/WienerNetzeSmartmeter/commit/2d69c65e66501d7e3d909507c9eedc920ab88597


Here is the script with the adjusted parameters that I have successfully tested.

I marked the changes

**test.py**
`from vienna_smartmeter import Smartmeter

username = 'jxxxxxxxxxxxx@xxxxxx.at'
password = 'xxxxxxxxxxx'

api = Smartmeter(username, password)
                         
print(api.profil())
print(api.consumptions())
print(api.base_information())
print(api.meter_readings())`

**client.py**
`"""Contains the Smartmeter API Client."""
import logging
from datetime import datetime
from urllib import parse

import requests
from lxml import html

from .errors import SmartmeterLoginError, SmartmeterConnectionError
from vienna_smartmeter import constants as const

logger = logging.getLogger(__name__)


class Smartmeter:
    """Smartmeter client."""

    def __init__(self, username, password, login=True):
        """Access the Smartmeter API.
        Args:
            username (str): Username used for API Login.
            password (str): Username used for API Login.
            login (bool, optional): If _login() should be called. Defaults to True.
        """
        self.username = username
        self.password = password
        self.session = requests.Session()
        self._access_token = None
        **self._refresh_token = None**
        self._api_gateway_token = None

        if login:
            self._login()

    def _login(self):
        login_url = const.AUTH_URL + "auth?" + parse.urlencode(const.LOGIN_ARGS)
        result = self.session.get(login_url)
        if result.status_code != 200:
            raise SmartmeterConnectionError(f"Could not load login page. Error: {result.content}")
        tree = html.fromstring(result.content)
        action = tree.xpath("(//form/@action)")[0]

        result = self.session.post(
            action,
            data={
                "username": self.username,
                "password": self.password,
            },
            allow_redirects=False,
        )

        if "Location" not in result.headers:
            raise SmartmeterLoginError("Login failed. Check username/password.")

        code = result.headers["Location"].split("&code=", 1)[1]

        result = self.session.post(
            const.AUTH_URL + "token",
            data = const.build_access_token_args(code=code),
        )

        if result.status_code != 200:
            raise SmartmeterConnectionError(f"Could not obtain access token: {result.content}")

        self._access_token = result.json()["access_token"]
        **self._refresh_token = result.json()["refresh_token"] # TODO: use this to refresh the token of this session instead of re-login. may be nicer for the API**
        self._api_gateway_token = self._get_api_key(self._access_token)

    def _get_api_key(self, token):
        headers = {
            "Authorization": f"Bearer {token}"
        }
        result = self.session.get(const.PAGE_URL, headers=headers)
        tree = html.fromstring(result.content)
        scripts = tree.xpath("(//script/@src)")
        for script in scripts:
            response = self.session.get(const.PAGE_URL + script)
            **for match in const.API_GATEWAY_TOKEN_REGEX.findall(response.text):
                return match
        raise SmartmeterConnectionError(
           "Could not obtain API key - no match"
        )**

    def _dt_string(self, datetime_string):
        return datetime_string.strftime(const.API_DATE_FORMAT)[:-3] + "Z"

    def _call_api(
        self,
        endpoint,
        base_url=None,
        method="GET",
        data=None,
        query=None,
        return_response=False,
    ):
        if base_url is None:
            base_url = const.API_URL
        url = "{0}{1}".format(base_url, endpoint)

        if query:
            url += ("?" if "?" not in endpoint else "&") + parse.urlencode(query)

        logger.debug("REQUEST: {}", url)

        headers = {
            "Authorization": f"Bearer {self._access_token}",
            "X-Gateway-APIKey": self._api_gateway_token
        }

        if data:
            logger.debug("DATA: {}", data)
            headers["Content-Type"] = "application/json"

        response = self.session.request(method, url, headers=headers, json=data)

        if return_response:
            return response

        return response.json()

    def _get_first_zaehlpunkt(self):
        return self.zaehlpunkte()[0]["zaehlpunkte"][0]["zaehlpunktnummer"]

    def zaehlpunkte(self):
        """Returns zaehlpunkte for currently logged in user."""
        return self._call_api("zaehlpunkte")

    **def consumptions(self):
        """Returns response from 'consumptions' endpoint."""
        return self._call_api("zaehlpunkt/consumptions")

    def base_information(self):
        """Returns response from 'baseInformation' endpoint."""
        return self._call_api("zaehlpunkt/baseInformation")

    def meter_readings(self):
        """Returns response from 'meterReadings' endpoint."""
        return self._call_api("zaehlpunkt/meterReadings")**
        
    def verbrauch_raw(self, date_from: datetime, date_to: datetime = None, zaehlpunkt = None):
        """Returns energy usage.
        Args:
            date_from (datetime): Start date for energy usage request
            date_to (datetime, optional): End date for energy usage request.
                Defaults to datetime.now().
            zaehlpunkt (str, optional): Id for desired smartmeter.
                If None check for first meter in user profile.
        Returns:
            dict: JSON response of api call to
                'messdaten/zaehlpunkt/ZAEHLPUNKT/verbrauchRaw'
        """
        if date_to is None:
            date_to = datetime.now()
        if zaehlpunkt is None:
            zaehlpunkt = self._get_first_zaehlpunkt()
        endpoint = "messdaten/zaehlpunkt/{}/verbrauchRaw".format(zaehlpunkt)
        query = {
            "dateFrom": self._dt_string(date_from),
            "dateTo": self._dt_string(date_to),
            "granularity": "DAY",
        }
        return self._call_api(endpoint, query=query)

    def verbrauch(self, date_from: datetime, date_to: datetime = None, zaehlpunkt = None):
        """Returns energy usage.
        Args:
            date_from (datetime.datetime): Starting date for energy usage request
            date_to (datetime.datetime, optional): Ending date for energy usage request.
                Defaults to datetime.datetime.now().
            zaehlpunkt (str, optional): Id for desired smartmeter.
                If None check for first meter in user profile.
        Returns:
            dict: JSON response of api call to
                'm/messdaten/zaehlpunkt/ZAEHLPUNKT/verbrauch'
        """
        if date_to is None:
            date_to = datetime.now()
        if zaehlpunkt is None:
            zaehlpunkt = self._get_first_zaehlpunkt()
        endpoint = "messdaten/zaehlpunkt/{}/verbrauch".format(zaehlpunkt)
        query = const.build_verbrauchs_args(
            dateFrom = self._dt_string(date_from),
            dateTo = self._dt_string(date_to)
        )
        return self._call_api(endpoint, query=query)

    def tages_verbrauch(self, day: datetime, zaehlpunkt = None):
        """Returns energy usage.
        Args:
            day (datetime.datetime): Day date for the request
            zaehlpunkt (str, optional): Id for desired smartmeter.
                If None check for first meter in user profile.
        Returns:
            dict: JSON response of api call to
                'messdaten/zaehlpunkt/ZAEHLPUNKT/verbrauch'
        """

        if zaehlpunkt is None:
            zaehlpunkt = self._get_first_zaehlpunkt()
        endpoint = "messdaten/zaehlpunkt/{}/verbrauch".format(zaehlpunkt)
        query = const.build_verbrauchs_args(
            dateFrom = self._dt_string(day.replace(hour=0, minute=0, second=0))
        )
        return self._call_api(endpoint, query=query)

    def profil(self):
        """Returns profil of logged in user.
        Returns:
            dict: JSON response of api call to 'user/profile'
        """
        return self._call_api("user/profile", const.API_URL_ALT)

    def ereignisse(self, date_from: datetime, date_to: datetime = None, zaehlpunkt = None):
        """Returns events between date_from and date_to of a specific smart meter.
        Args:
            date_from (datetime.datetime): Starting date for request
            date_to (datetime.datetime, optional): Ending date for request.
                Defaults to datetime.datetime.now().
            zaehlpunkt (str, optional): Id for desired smart meter.
                If is None check for first meter in user profile.
        Returns:
            dict: JSON response of api call to 'user/ereignisse'
        """
        if date_to is None:
            date_to = datetime.now()
        if zaehlpunkt is None:
            zaehlpunkt = self._get_first_zaehlpunkt()
        query = {
            "zaehlpunkt": zaehlpunkt,
            "dateFrom": self._dt_string(date_from),
            "dateUntil": self._dt_string(date_to),
        }
        return self._call_api("user/ereignisse", const.API_URL_ALT, query=query)

    def create_ereignis(self, zaehlpunkt, name, date_from, date_to=None):
        """Creates new event.
        Args:
            zaehlpunkt (str): Id for desired smartmeter.
                If None check for first meter in user profile
            name (str): Event name
            date_from (datetime.datetime): (Starting) date for request
            date_to (datetime.datetime, optional): Ending date for request.
        Returns:
            dict: JSON response of api call to 'user/ereignis'
        """
        if date_to is None:
            dto = None
            typ = "ZEITPUNKT"
        else:
            dto = self._dt_string(date_to)
            typ = "ZEITSPANNE"

        data = {
            "endAt": dto,
            "name": name,
            "startAt": self._dt_string(date_from),
            "typ": typ,
            "zaehlpunkt": zaehlpunkt,
        }

        return self._call_api("user/ereignis", data=data, method="POST")

    def delete_ereignis(self, ereignis_id):
        """Deletes ereignis."""
        return self._call_api("user/ereignis/{}".format(ereignis_id), method="DELETE")`

**constants.py**
`import re

MAIN_SCRIPT_REGEX = re.compile("^main\S+\.js$")
**API_GATEWAY_TOKEN_REGEX = re.compile(r'b2cApiKey\:\s*\"([A-Za-z0-9\-_]+)\"', re.IGNORECASE)**

PAGE_URL = "https://smartmeter-web.wienernetze.at/"
API_URL_ALT = "https://service.wienernetze.at/sm/api/"
API_URL = "https://api.wstw.at/gateway/WN_SMART_METER_PORTAL_API_B2C/1.0/"
REDIRECT_URI = "https://smartmeter-web.wienernetze.at/"
API_DATE_FORMAT = "%Y-%m-%dT%H:%M:%S.%f"
AUTH_URL = "https://log.wien/auth/realms/logwien/protocol/openid-connect/"  # noqa


LOGIN_ARGS = {
    "client_id": "wn-smartmeter",
    "redirect_uri": REDIRECT_URI,
    "response_mode": "fragment",
    "response_type": "code",
    "scope": "openid",
    "nonce": "",
}

def build_access_token_args(**kwargs):
    args = {
        "grant_type": "authorization_code",
        "client_id": "wn-smartmeter",
        "redirect_uri": REDIRECT_URI,
    }
    args.update(**kwargs)
    return args

def build_verbrauchs_args(**kwargs):
    args = {
        "period": "DAY",
        "accumulate": False,
        "offset": 0,
        "dayViewResolution": "QUARTER-HOUR",
    }
    args.update(**kwargs)
    return `

**Comment by fhempy** [comment]
Thank you for providing the diff. Please test with the latest version I just released.

**Comment by fhempy** [comment]
Have you had time to do a quick test?

**Comment by schami23** [comment]
Unfortunately it doesn't work, I don't know what it is. I installed the asyncio module, I don't know if I'm still missing something?

There is nothing in the log file either. How can I check the function? Unfortunately, I'm not very familiar with Python.

**Comment by fhempy** [comment]
I found the bug in the login code. Can you please try with the latest version: 0.1.620

**Comment by schami23** [comment]
yes, great now it works.
Thank you

**Comment by schami23** [comment]
Here the Readings

```
Readings
consumptionDayBeforeYesterday_date		2023-03-08T23:00:00.000Z		2023-03-11 08:29:38
consumptionDayBeforeYesterday_validated		1					2023-03-11 08:29:38
consumptionDayBeforeYesterday_value		8680					2023-03-11 08:29:38
consumptionYesterday_date			2023-03-09T23:00:00.000Z		2023-03-11 08:29:38
consumptionYesterday_validated			1					2023-03-11 08:29:38
consumptionYesterday_value			10845					2023-03-11 08:29:38
hasSmartMeter					1					2023-03-11 08:29:37
isDataDeleted					0					2023-03-11 08:29:37
meterReadings_0_date				2023-03-09T23:00:00.000Z		2023-03-11 08:29:39
meterReadings_0_type				1-2:1.8.0				2023-03-11 08:29:39
meterReadings_0_validated			1					2023-03-11 08:29:39
meterReadings_0_value				1990241					2023-03-11 08:29:39
zaehlpunkt_adresse				Mustergasse 1, 1010 Wien		2023-03-11 08:29:37
zaehlpunkt_postleitzahl				1010					2023-03-11 08:29:37
zaehlpunkt_zaehlpunktAnlagentyp			TAGSTROM				2023-03-11 08:29:37
zaehlpunkt_zaehlpunktnummer			AT001000000000000000100000000012	2023-03-11 08:29:37
```

**Comment by fhempy** [comment]
Great! Thank you for providing the readings as well. I just take all the data I get from the API and convert it to readings, therefore it might look a little bit weird with the `_value` name. Nevertheless I would like to keep it that way, as it assures that the module can handle other values as well.

I'm going to close the issue. Please open another one if you have any issues or would like to have some adoptions.
