### ISSUE TITLE
Tuya Smartlife device

### ISSUE THREAD

**Issue by malcb** [fhempy/fhempy#479]
I've defined a tuya_smartlife and that seems to be all working.  It has found my WiFi Smartlight.  I can turn it on and off but the icon does not change.  I can change the work mode to scene (leds go green), and to music (leds go red), and to colour (leds go blue).  Setting to white does nothing.  Setting work mode to colour and then colour data (to a anything) gives this error:

Failed to execute function Set: Traceback (most recent call last):
  File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.9/site-packages/fhempy/lib/fhem_pythonbinding.py", line 385, in handle_function
    ret = await self.execute_function(hash, fhem_reply_done, nmInstance)
  File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.9/site-packages/fhempy/lib/fhem_pythonbinding.py", line 484, in execute_function
    ret = await asyncio.wait_for(
  File "/usr/lib/python3.9/asyncio/tasks.py", line 481, in wait_for
    return fut.result()
  File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.9/site-packages/fhempy/lib/generic.py", line 208, in Set
    return await utils.handle_set(self._conf_set, self, hash, args, argsh)
  File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.9/site-packages/fhempy/lib/utils.py", line 340, in handle_set
    return await fct_call(hash, final_params)
  File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.9/site-packages/fhempy/lib/tuya_smartlife/tuya_smartlife.py", line 78, in set_colour_data
    await self.device.set_colour_data(hash, params)
  File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.9/site-packages/fhempy/lib/tuya_smartlife/tuya_smartlife_device.py", line 201, in set_colour_data
    if self._t_info["category"] == "dj":
TypeError: 'CustomerDevice' object is not subscriptable

Selecting in set music_data or control_data brings up a text box which will accept numbers or text.  I don't what this wants but anything I try just throws an error like this:

Failed to execute function Set: Traceback (most recent call last):
  File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.9/site-packages/fhempy/lib/fhem_pythonbinding.py", line 385, in handle_function
    ret = await self.execute_function(hash, fhem_reply_done, nmInstance)
  File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.9/site-packages/fhempy/lib/fhem_pythonbinding.py", line 484, in execute_function
    ret = await asyncio.wait_for(
  File "/usr/lib/python3.9/asyncio/tasks.py", line 481, in wait_for
    return fut.result()
  File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.9/site-packages/fhempy/lib/generic.py", line 208, in Set
    return await utils.handle_set(self._conf_set, self, hash, args, argsh)
  File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.9/site-packages/fhempy/lib/utils.py", line 340, in handle_set
    return await fct_call(hash, final_params)
  File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.9/site-packages/fhempy/lib/tuya_smartlife/tuya_smartlife.py", line 69, in set_json
    await self.device.set_json(hash, params)
  File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.9/site-packages/fhempy/lib/tuya_smartlife/tuya_smartlife_device.py", line 190, in set_json
    await self.send_commands(
  File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.9/site-packages/fhempy/lib/tuya_smartlife/tuya_smartlife_device.py", line 225, in send_commands
    await self.tuyaiot.send_commands(self._t_deviceid, commands)
  File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.9/site-packages/fhempy/lib/tuya_smartlife/tuya_smartlife_setup.py", line 280, in send_commands
    await utils.run_blocking(
  File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.9/site-packages/fhempy/lib/utils.py", line 72, in run_blocking
    return await asyncio.get_event_loop().run_in_executor(pool, function)
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.9/site-packages/tuya_sharing/manager.py", line 93, in send_commands
    return self.device_repository.send_commands(device_id, commands)
  File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.9/site-packages/tuya_sharing/device.py", line 180, in send_commands
    self.api.post(f"/v1.1/m/thing/{device_id}/commands", None, {"commands": commands})
  File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.9/site-packages/tuya_sharing/customerapi.py", line 192, in post
    return self.__request("POST", path, params, body)
  File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.9/site-packages/tuya_sharing/customerapi.py", line 121, in __request
    raise Exception(f"network error:({ret['code']}) {ret['msg']}")
Exception: network error:(SYSTEM_ERROR) Server Error

**Comment by fhempy** [comment]
Please test with the latest version.

**Comment by malcb** [comment]
I decided that upgrading my Raspberry PI from bullseye to bookworm was the easiest way
to get python3.11 and I followed this:

https://www.linuxfordevices.com/tutorials/linux/upgrade-raspberry-pi-os

Note, for others trying the same, my PI had an another source in /etc/apt/sources.list.d/raspi.list which also needed changing

My PI now has 3.11.2 and I think it has automatically removed 3.9.  I now get this error:

Activating virtual environment...OK
2025-01-01 15:16:03,589 - ERROR    - __main__: Failed to load fhempy
Traceback (most recent call last):
  File "/opt/fhem/FHEM/bindings/python/bin/start_fhempy.py", line 141, in <module>
    import fhempy.lib.fhem_pythonbinding as fpb
ModuleNotFoundError: No module named 'fhempy'
2025-01-01 15:16:03,700 - INFO     - __main__: Attempting install of fhempy>=0.1.462
2025-01-01 15:16:04,316 - ERROR    - __main__: Unable to install package fhempy>=0.1.462: /opt/fhem/.fhempy/fhempy_venv/bin/python3: No module named pip
2025-01-01 15:16:04,325 - ERROR    - __main__: Failed to install fhempy, exit now...

I notice in /opt/fhem/.fhempy/fhempy_venv/bin there is a pip3.9 and python3.9.  Do I need to put python3.9 back?  Or revises these for python3.11?  And if the latter what is the easiest method to do that?  I can't seem to get fhem/fhempy to do this.

thanks

**Comment by malcb** [comment]
I decided that upgrading my Raspberry PI from bullseye to bookworm was the easiest way
to get python3.11 and I followed this:

https://www.linuxfordevices.com/tutorials/linux/upgrade-raspberry-pi-os

Note, for others trying the same, my PI had an another source in /etc/apt/sources.list.d/raspi.list which also needed changing

My PI now has 3.11.2 and I think it has automatically removed 3.9.  I now get this error:

Activating virtual environment...OK
2025-01-01 15:16:03,589 - ERROR    - __main__: Failed to load fhempy
Traceback (most recent call last):
  File "/opt/fhem/FHEM/bindings/python/bin/start_fhempy.py", line 141, in <module>
    import fhempy.lib.fhem_pythonbinding as fpb
ModuleNotFoundError: No module named 'fhempy'
2025-01-01 15:16:03,700 - INFO     - __main__: Attempting install of fhempy>=0.1.462
2025-01-01 15:16:04,316 - ERROR    - __main__: Unable to install package fhempy>=0.1.462: /opt/fhem/.fhempy/fhempy_venv/bin/python3: No module named pip
2025-01-01 15:16:04,325 - ERROR    - __main__: Failed to install fhempy, exit now...

I notice in /opt/fhem/.fhempy/fhempy_venv/bin there is a pip3.9 and python3.9.  Do I need to put python3.9 back?  Or revises these for python3.11?  And if the latter what is the easiest method to do that?  I can't seem to get fhem/fhempy to do this.

thanks

**Comment by malcb** [comment]
BTW from commandline "pip list" and "pip3 list" both return a list of modules so pip does exist.

**Comment by denis-robel** [comment]
When I install tuya smartlife integration I get following error:

`2025-01-06 10:32:59,474 - ERROR    - fhempy.lib.pkg_installer: Unable to install package cryptography==43.0.0: error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      error: failed to parse manifest at `/tmp/pip-install-w2r7f513/cryptography_e294b26cd86549ecb7fd8da127e87d7d/src/rust/Cargo.toml`
      
      Caused by:
        invalid type: map, expected a sequence for key `package.authors`
      💥 maturin failed
        Caused by: Cargo metadata failed. Does your crate compile with `cargo build`?
        Caused by: `cargo metadata` exited with an error:
      Error running maturin: Command '['maturin', 'pep517', 'write-dist-info', '--metadata-directory', '/tmp/pip-modern-metadata-nzwhxv3o', '--interpreter', '/opt/fhem/.fhempy/fhempy_venv/bin/python3']' returned non-zero exit status 1.
      Checking for Rust toolchain....
      Running `maturin pep517 write-dist-info --metadata-directory /tmp/pip-modern-metadata-nzwhxv3o --interpreter /opt/fhem/.fhempy/fhempy_venv/bin/python3`
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.

[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: pip install --upgrade pip
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
`
My system is Raspi4 on Bullseye with python 3.12.5.
There is a problem with maturin / cargo.

How can I fix this?

**Comment by denis-robel** [comment]
Ok, I fixed the problem:
in FHEM/bindings/python/fhempy/lib/tuya_smartlife/manifest.json I set the requirements for cryptography to "cryptography==44.0.0"

**Comment by malcb** [comment]
I've finally managed to get back to working with python 3.11 so to help others this is what I did:

As mentioned above I upgraded my (raspberry pi) bullseye to bookworm in order to get python 3.11.  fhempy still had problems so I did a re-install of fhempy like this:

in fhem I edited the fhem config file and remove all the fhempy stuff including all the defines for fhempy modules.  I saved this removed text as I'll need the defines later.  In fhem I shutdown fhem.  In a terminal I did:

```
systemctl stop fhem
sudo -u fhem bash
source /opt/fhem/.fhempy/fhempy_venv/bin/activate
pip3 uninstall fhempy
deactivate
exit
```
The prompt changes during those steps so you can tell they are working

Next delete the python virtual environment by removing /opt/fhem/.fhempy
I then did an atp update and atp full-upgrade just to be sure my pi had the most recent files, and then a reboot to restart fhem

I now have a clean fhem with no fhempy stuff but all the setup for fhempy because this is re-install.
Then I did fhem update (which was nothing to do) which also confirmed I still have the update inclusion for fhempy.
Then I reinstalled fhempy as per instructions with "define fhempy_local BindingsIo fhempy" in fhem.

I then waited for this to complete.  I watch this with htop in my terminal window, waiting for CPU to fall below 100% (I have an old PI).  Then I added back each of the fhempy define lines I had removed (see text saved from fhem config file) and I did this one at a time, waiting for the install to complete (i.e. with htop),

Finally I got to tuya_smartlife which failed "Attempting install of cryptography==43.0.0" as reported in the fhempy server log file.  I changed /opt/fhem/.fhempy/fhempy_venv/lib/python3.11/site-packages/fhempy/lib/tuya_smartlife/manifest.json so that it said "cryptography==44.0.0", saved the file and rebooted fhem.  Module tuya_smartlife then installed ok.

**Comment by malcb** [comment]
Going back to my initial problem, even with python 3.11 this still exists,  the error reported now when I try to change the smartlight colour data is:

> Failed to execute function Set: Traceback (most recent call last):
>   File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.11/site-packages/fhempy/lib/fhem_pythonbinding.py", line 385, in handle_function
>     ret = await self.execute_function(hash, fhem_reply_done, nmInstance)
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.11/site-packages/fhempy/lib/fhem_pythonbinding.py", line 484, in execute_function
>     ret = await asyncio.wait_for(
>           ^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.11/asyncio/tasks.py", line 479, in wait_for
>     return fut.result()
>            ^^^^^^^^^^^^
>   File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.11/site-packages/fhempy/lib/generic.py", line 208, in Set
>     return await utils.handle_set(self._conf_set, self, hash, args, argsh)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.11/site-packages/fhempy/lib/utils.py", line 340, in handle_set
>     return await fct_call(hash, final_params)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.11/site-packages/fhempy/lib/tuya_smartlife/tuya_smartlife.py", line 78, in set_colour_data
>     await self.device.set_colour_data(hash, params)
>   File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.11/site-packages/fhempy/lib/tuya_smartlife/tuya_smartlife_device.py", line 201, in set_colour_data
>     if self._t_info["category"] == "dj":
>        ~~~~~~~~~~~~^^^^^^^^^^^^
> TypeError: 'CustomerDevice' object is not subscriptable
 
I've also got tuya_local installed too.  The fhempy server log says:

> 2025-01-07 11:50:32,876 - ERROR    - fhempy.lib.fhem_pythonbinding: Failed to execute function Set: Traceback (most recent call last):
>   File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.11/site-packages/fhempy/lib/fhem_pythonbinding.py", line 385, in handle_function
>     ret = await self.execute_function(hash, fhem_reply_done, nmInstance)
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.11/site-packages/fhempy/lib/fhem_pythonbinding.py", line 484, in execute_function
>     ret = await asyncio.wait_for(
>           ^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.11/asyncio/tasks.py", line 479, in wait_for
>     return fut.result()
>            ^^^^^^^^^^^^
>   File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.11/site-packages/fhempy/lib/generic.py", line 208, in Set
>     return await utils.handle_set(self._conf_set, self, hash, args, argsh)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.11/site-packages/fhempy/lib/utils.py", line 340, in handle_set
>     return await fct_call(hash, final_params)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.11/site-packages/fhempy/lib/tuya_smartlife/tuya_smartlife.py", line 78, in set_colour_data
>     await self.device.set_colour_data(hash, params)
>   File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.11/site-packages/fhempy/lib/tuya_smartlife/tuya_smartlife_device.py", line 201, in set_colour_data
>     if self._t_info["category"] == "dj":
>        ~~~~~~~~~~~~^^^^^^^^^^^^
> TypeError: 'CustomerDevice' object is not subscriptable
>  with hash: {'FHEMPYTYPE': 'tuya_smartlife', 'NAME': 'tuya_smartlife_bf08a0160db18905749i6r', 'msgtype': 'function', 'function': 'Set', 'args': ['tuya_smartlife_bf08a0160db18905749i6r', 'colour_data', '0000FF'], 'PYTHONTYPE': 'tuya_smartlife', 'defargs': ['tuya_smartlife_bf08a0160db18905749i6r', 'fhempy', 'tuya_smartlife', 'tuya_smartlife_integration', 'bf08a0160db18905749i6r'], 'argsh': {}, 'defargsh': {}, 'id': 48570443}

I also have these warnings in the log file that might be relevant:

> 2025-01-07 11:03:10,395 - WARNING  - tuya_local_bf08a0160db18905749i6r: dp_27 in spec but not found locally. This should be reported to TuYa
> 2025-01-07 11:03:10,507 - WARNING  - tuya_local_bf08a0160db18905749i6r: dp_28 in spec but not found locally. This should be reported to TuYa
> 

Overall the change to python 3.11 has made no difference.

**Comment by malcb** [comment]
FYI changing /opt/fhem/.fhempy/fhempy_venv/lib/python3.11/site-packages/fhempy/lib/tuya_smartlife/manifest.json so that it says "cryptography>=43.0.0" works too with version 44.

**Comment by ThMuellerFPT** [comment]
Is there already a solution to the current problem?

**Comment by malcb** [comment]
Updated to latest.  BTW there is still has the issue that cryptography must be 43.0.0 rather than 43 or above.  Version 44 is available as binary whereas 43 has to be built which takes hours, if it even succeeds.  Still get the same error when trying to set colour data:

```
Failed to execute function Set: Traceback (most recent call last):
  File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.11/site-packages/fhempy/lib/fhem_pythonbinding.py", line 385, in handle_function
    ret = await self.execute_function(hash, fhem_reply_done, nmInstance)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.11/site-packages/fhempy/lib/fhem_pythonbinding.py", line 484, in execute_function
    ret = await asyncio.wait_for(
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/tasks.py", line 479, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.11/site-packages/fhempy/lib/generic.py", line 208, in Set
    return await utils.handle_set(self._conf_set, self, hash, args, argsh)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.11/site-packages/fhempy/lib/utils.py", line 340, in handle_set
    return await fct_call(hash, final_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.11/site-packages/fhempy/lib/tuya_smartlife/tuya_smartlife.py", line 78, in set_colour_data
    await self.device.set_colour_data(hash, params)
  File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.11/site-packages/fhempy/lib/tuya_smartlife/tuya_smartlife_device.py", line 201, in set_colour_data
    if self._t_info["category"] == "dj":
       ~~~~~~~~~~~~^^^^^^^^^^^^
TypeError: 'CustomerDevice' object is not subscriptable

```

**Comment by malcb** [comment]
Latest fhempy update has not fixed this issue.  Still have same fault.  Still have cryptography must be 43.0.0 rather than 44.0.0 which is the version available as binary for raspberry pi bookworm.

**Comment by malcb** [comment]
Just upgraded fhempy to 0.1.751.  Files in /opt/fhem/.fhempy/fhempy_venv/lib/python3.11/site-packages/fhempy/lib/tuya_smartlife now dated 28/2/2025 18:19:47 so these have been changed by fhempy.  manifest.json still requires cryptography 43.0.0 so I had to edit this is be 44.0.0 which is the binary version available for the raspberry PI (bookworm).  Not sure if this has messed up the upgrade as I had to shutdown fhem in the middle so I could fix manifest.json.  Files in _pycache_ are 28/2/2025 18:21:01/02 where as manifest.json is 28/2/2025 18:21:15.  So I forced a recompile by deleting all the files in _pycache_ and restarting fhem.  Files in _pycache_ are now all 2/3/2025.  But maybe I need to delete in another pycache too?

Fault when trying so set colour value is still the same as before, "not subscriptable".

**Comment by malcb** [comment]
BTW I also tried deleting cache files in /opt/fhem/.fhempy/fhempy_venv/lib/python3.11/site-packages/fhempy/lib/__pycache__ but this made no difference to the fault.

**Comment by malcb** [comment]
Just upgraded fhempy to 0.1.752.  Fault still present.
